name: Rescrape

on:
  schedule:
    - cron: '0 8 * * MON'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Rescrape
        run: |
          python mountains.py

      - name: Commit & Push Changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit mountains.json -m "[Automated]: Update data"
          git push
